ASUIS-280: Launch the Web Directory component.
ASUWebPlatforms/webspark-module-webspark_webdir pull request #1
Opened 2022-03-29 05:30 UTC by georgebaev

@mlsamuelson this adds the functionality to launch the Web Directory component.

Ref.: https://asudev.jira.com/browse/ASUIS-280

2022-03-29 19:36 UTC, mlsamuelson requested changes
This looks good. I like the data-attribute approach you've taken. 

Some minor changes requested.

2022-03-29 19:36 UTC, mlsamuelson commented on js/webspark_webdir.js
> +(function ($, Drupal, drupalSettings, once) {
Since you're using data-* attributes to pass the settings, you don't need `drupalSettings`.

2022-03-29 19:36 UTC, mlsamuelson commented on js/webspark_webdir.js
> +})(jQuery, Drupal, drupalSettings, once);
`drupalSettings` not needed.

2022-03-29 19:36 UTC, mlsamuelson commented on webspark_webdir.libraries.yml
> +    - core/drupalSettings
`drupalSettings` not used.

2022-03-30 04:27 UTC, georgebaev commented on js/webspark_webdir.js
> +(function ($, Drupal, drupalSettings, once) {
I removed the `drupalSettings` parameter.

2022-03-30 04:27 UTC, georgebaev commented on js/webspark_webdir.js
> +})(jQuery, Drupal, drupalSettings, once);
I removed `drupalSettings`

2022-03-30 04:27 UTC, georgebaev commented on webspark_webdir.libraries.yml
> +    - core/drupalSettings
Removed.

2022-03-30 14:35 UTC, mlsamuelson approved these changes

2022-03-30 14:35 UTC, merged