ASUIS-760: Webspark Webdir module shows wrong affiliations in Layout Builder interface
ASUWebPlatforms/webspark-module-webspark_webdir pull request #34
Opened 2022-08-23 22:07 UTC by tbutterf

This PR resolves ASUIS-760 as well as ASUIS-799 (In people Component type, clicking on parent does not add to list). It also adds parent/child relationships for when multiple units are selected and people exist in more than one unit.
See:
https://asudev.jira.com/browse/ASUIS-760
https://asudev.jira.com/browse/ASUIS-799

2022-08-26 19:50 UTC, mlsamuelson commented on jquery-plugin/jstree/dist/jstree.min.js
> +!function (a) {
Please keep minified.

2022-08-26 20:09 UTC, mlsamuelson requested changes

2022-08-26 20:09 UTC, mlsamuelson commented on js/add-field.js
> +              update_tree();
Check that `default_values` isn't needed. If this wasn't intentional.

2022-08-26 20:09 UTC, mlsamuelson commented on js/add-field.js
> +          if (departments.length > 1) {
Let's add a comment here to identify that this is what handles the nesting when multiple depts, in the UI.

2022-08-26 22:00 UTC, tbutterf commented on jquery-plugin/jstree/dist/jstree.min.js
> +!function (a) {
Done.

2022-08-26 22:01 UTC, tbutterf commented on js/add-field.js
> +              update_tree();
added back.

2022-08-26 22:01 UTC, tbutterf commented on js/add-field.js
> +          if (departments.length > 1) {
comment added.

2022-08-30 19:00 UTC, mlsamuelson approved these changes
Thank you for the updates. Next person who has to debug an issue here will owe you one, @tbutterf . ;)

2022-08-30 19:01 UTC, merged